export const STORE_PATH = {
  KEY: 'KEY',
  RELATIONS: 'RELATIONS',
  DATA: 'ENTITIES',
  ENTITIES_STATE: 'ENTITIES_STATE',
  STATE: 'STATE',
  ENTITY_STATE: {
    STATE: 'STATE',
    STATUS: 'STATUS',
    ACTIONS: 'ACTIONS',
    HISTORY_INDEX: 'HISTORY_INDEX',
  },
};

export const ENTITY_STATUS = {
  SYNCED: 'SYNCED',
  SYNC_FAILED: 'SYNC_FAILED',
  SYNCING: 'SYNCING',
  OUT_OF_SYNC: 'OUT_OF_SYNC',
};

export const ENTITY_STATE = {
  NEW: 'NEW',
  EXISTING: 'EXISTING',
  ID_UPDATED: 'ID_UPDATED',
  DELETED: 'DELETED',
};

export const ACTION = {
  DELETE: 'DELETE',
  UPDATE: 'UPDATE',
  LOAD: 'LOAD',
};

export const STORE_KEY = 'RRECORDS';
