export const STORE_PATH = {
  KEY: 'KEY',
  DATA: 'ENTITIES',
  STATE: 'STATE',
  ACTIONS: 'ACTIONS',
  ENTITIES_STATE: 'ENTITIES_STATE',
};

export const ENTITY_STATE = {
  NEW: 'NEW',
  SYNCED: 'SYNCED',
  SYNC_FAILED: 'SYNC_FAILED',
  SYNCING: 'SYNCING',
  OUT_OF_SYNC: 'OUT_OF_SYNC',
  ID_UPDATED: 'ID_UPDATED',
};

export const ACTION = {
  DELETE: 'DELETE',
  UPDATE: 'UPDATE',
};

export const STORE_KEY = 'RRECORDS';
