const RRECORDS = '$$RRECORDS';
const constantsFactory = ID => ({
  LOAD: `${RRECORDS}/${ID}/LOAD`,
  LOAD_FAILED: `${RRECORDS}/${ID}/LOAD_FAILED`,
  LOAD_SUCCEEDED: `${RRECORDS}/${ID}/LOAD_SUCCEEDED`,
  UPDATE: `${RRECORDS}/${ID}/UPDATE`,
  UPDATE_FAILED: `${RRECORDS}/${ID}/UPDATE_FAILED`,
  UPDATE_SUCCEEDED: `${RRECORDS}/${ID}/UPDATE_SUCCEEDED`,
  DELETE: `${RRECORDS}/${ID}/DELETE`,
  DELETE_FAILED: `${RRECORDS}/${ID}/DELETE_FAILED`,
  DELETE_SUCCEEDED: `${RRECORDS}/${ID}/DELETE_SUCCEEDED`,
  SYNC_ALL: `${RRECORDS}/${ID}/SYNC_ALL`,
});

export default constantsFactory;
